Missing import
packages/apps/Launcher3/quickstep/src/com/android/quickstep/views/MemInfoView.java:99: 
error: could not resolve HandlerThread
private static final HandlerThread BACKGROUND_THREAD = new HandlerThread("MemoryInfoThread");